SELECT *
FROM PAIS
ORDER BY NOME DESC;

SELECT LOGRADOURO, CEP
FROM ENDERECO
WHERE UPPER(LOGRADOURO) LIKE 'A%';

SELECT *
FROM ENDERECO
WHERE CEP LIKE '%0';

SELECT *
FROM ENDERECO
WHERE NUMERO BETWEEN 1 AND 100;

SELECT *
FROM ENDERECO
WHERE UPPER(LOGRADOURO) LIKE 'RUA%'
ORDER BY CEP DESC;

SELECT COUNT(*) AS TOTAL_ENDERECOS
FROM ENDERECO;

ALTER TABLE ENDERECO
ADD ID_CIDADE NUMBER(3);

UPDATE ENDERECO E
SET ID_CIDADE = (
    SELECT B.ID_CIDADE
    FROM BAIRRO B
    WHERE B.ID_BAIRRO = E.ID_BAIRRO
);

ALTER TABLE ENDERECO
ADD CONSTRAINT FK_ENDERECO_CIDADE
FOREIGN KEY (ID_CIDADE)
REFERENCES CIDADE(ID_CIDADE);

SELECT ID_CIDADE, COUNT(*) AS QTDE_ENDERECOS
FROM ENDERECO
GROUP BY ID_CIDADE
ORDER BY ID_CIDADE;
