-- Criar uma tabela

CREATE TABLE VEM_SER.PERSONAGEM (
	id_personagem NUMBER(38,0) PRIMARY KEY NOT NULL,
	nivel NUMBER(38,0) NOT NULL,
	nickname VARCHAR2(30) NOT NULL,
	agilidade NUMBER(38,0) NOT NULL,
	furtividade NUMBER(38,0) NOT NULL,
	forca NUMBER(38,0) NOT NULL,
	defesa NUMBER(38,0) NOT NULL,
	vida NUMBER(38,0) NOT NULL
);

-- Criar a sequence principal

CREATE SEQUENCE VEM_SER.SEQ_PERSONAGEM
START WITH 1
INCREMENT BY 1
NOCACHE NOCYCLE;

ALTER TABLE VEM_SER.PERSONAGEM
ADD classe_personagem VARCHAR(20) NOT NULL;

CREATE TABLE VEM_SER.BATALHA (
	id_batalha NUMBER(38,0) PRIMARY KEY NOT NULL,	
	id_personagem NUMBER(38,0) NOT NULL,
	inimigo VARCHAR(30) NOT NULL,
	CONSTRAINT FK_BATALHA_PERSONAGEM FOREIGN KEY (id_personagem) REFERENCES PERSONAGEM (id_personagem)
);
