UPDATE ENDERECO
SET LOGRADOURO = 'Logradouro Atualizado',
    COMPLEMENTO = 'Complemento Atualizado'
WHERE ID_ENDERECO IN (1002, 1003);

UPDATE ENDERECO
SET NUMERO = 999999
WHERE ID_ENDERECO = 1004;

DELETE FROM ENDERECO
WHERE ID_ENDERECO = (SELECT MAX(ID_ENDERECO) FROM ENDERECO);

DELETE FROM ENDERECO
WHERE NUMERO = 999999;

DELETE FROM ENDERECO
WHERE ID_ENDERECO IN (1001, 1002);